# book table

booksTable:
  Type: AWS::DynamoDB::Table
  Properties:
    AttributeDefinitions: 
      - AttributeName: "bookId"
        AttributeType: "S"

    BillingMode: PAY_PER_REQUEST   
    KeySchema: 
      - AttributeName: "bookId"
        KeyType: "HASH"   
    Tags: 
      - Key: Name
        Value: books_table