# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: wwwcloudstudio
# "service" is the name of this project. This will also be added to your AWS resource names.
service: slsauctions
frameworkVersion: 3.39.0
#frameworkVersion: 4.1.22

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-east-1

resources: 
  Resources:  
    ${file(resources.yml)}
    #- ${file(slsResources/cognitos.yml)}
    #- ${file(slsResources/dynamodbs.yml)}
    

plugins:
  - serverless-appsync-plugin

custom:
  appSync:
    name:  AuctionsAppSyncAPI
    authenticationType: AMAZON_COGNITO_USER_POOLS

    userPoolConfig:
      awsRegion: ${self:provider.region}
      defaultAction: ALLOW
      userPoolId: !Ref cognitoUserPool 

    mappingTemplatesLocation: mapping-templates
    mappingTemplates:
      - type: Query
        field: getUser
        dataSource: userTable

      - type: Mutation
        field: createUser
        dataSource: userTable

      - type: Mutation
        field: createAuction
        dataSource: auctionTable

    dataSources:
      - type: AMAZON_DYNAMODB

        name: userTable
        config: 
          tableName: !Ref userTable

      - type: AMAZON_DYNAMODB

        name: auctionTable
        config: 
          tableName: !Ref auctionTable

