
service: Auctions
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

resources: 
  - ${file(slsResources/cognitos.yml)}
  - ${file(slsResources/dyn_tables.yml)}

plugins:
  - serverless-appsync-plugin

custom:
  appSync:
    name:  AuctionsAppSyncAPI   
    schema: schema.graphql
    authenticationType: AMAZON_COGNITO_USER_POOLS

    userPoolConfig:
      awsRegion: ${self:provider.region}
      defaultAction: ALLOW
      userPoolId: !Ref cognitoUserPool 

    mappingTemplatesLocation: mapping-templates
    mappingTemplates:
      - type: Query
        field: getUser
        dataSource: xAuctionsTable

      - type: Query
        field: getAuction
        dataSource: xAuctionsTable

      - type: Query
        field: listAuctions
        dataSource: xAuctionsTable

      - type: Query
        field: getBids
        dataSource: xAuctionsTable     
      
      - type: Mutation
        field: addUser
        dataSource: xAuctionsTable

      - type: Mutation
        field: createAuction
        dataSource: xAuctionsTable

      - type: Mutation
        field: updateAuction
        dataSource: xAuctionsTable

      - type: Mutation
        field: deleteAuction
        dataSource: xAuctionsTable

      - type: Mutation
        field: createBid
        dataSource: xAuctionsTable

      - type: Mutation
        field: deleteBid
        dataSource: xAuctionsTable


    dataSources:
      - type: AMAZON_DYNAMODB
        name: xAuctionsTable
        config: 
          tableName: !Ref xAuctionsTable









