
Resources:

 # xAuctions Table

  xAuctionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:

        - AttributeName: "pk"
          AttributeType: "S"

        - AttributeName: "sk"
          AttributeType: "S"

        - AttributeName: "title"
          AttributeType: "S"

        - AttributeName: "gsi-1"
          AttributeType: "S"

        - AttributeName: "gsi-2"
          AttributeType: "S"

        - AttributeName: "gsi-3"
          AttributeType: "S"
      

      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"

      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"

        - AttributeName: "sk"
          KeyType: "RANGE"

      GlobalSecondaryIndexes: 
      
        - IndexName: "filterByStatus"
          KeySchema: 
            - AttributeName: "gsi-1"
              KeyType: "HASH"

            - AttributeName: "sk"
              KeyType: "RANGE" 

          ProvisionedThroughput: 
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
        
          Projection: 
            ProjectionType: ALL  

        - IndexName: "filterbyTitle"
          KeySchema: 
            - AttributeName: "sk"
              KeyType: "HASH"

            - AttributeName: "title"
              KeyType: "RANGE" 

          ProvisionedThroughput: 
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
        
          Projection: 
            ProjectionType: ALL  

        - IndexName: "filterbyCategory"
          KeySchema: 
            - AttributeName: "gsi-2"
              KeyType: "HASH"

            - AttributeName: "sk"
              KeyType: "RANGE" 

          ProvisionedThroughput: 
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
        
          Projection: 
            ProjectionType: ALL  

        - IndexName: "filterByAuctionEndDate"
          KeySchema: 
            - AttributeName: "sk"
              KeyType: "HASH"

            - AttributeName: "gsi-3"
              KeyType: "RANGE" 

          ProvisionedThroughput: 
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
        
          Projection: 
            ProjectionType: ALL  

      Tags:
        - Key: Name
          Value: tblXAuctions


 
  
