name: Auctions App

on:
  push:
    branches:
      - dev

jobs:
  devDeployment:
    name: dev.deployment
    runs-on: ubuntu-latest
    environment:
      name: test
      url: https://w3cloudstudio.com
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      name: Install Plugin and Deploy
      uses: serverless/github-action@v3.2
      with:
        args: -c "serverless plugin install --name serverless-appsync-plugin && serverless deploy --stage test"
        entrypoint: /bin/sh
      env:     
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        